FULL_NAME_CSS = '#userName'
EMAIL_CSS = '#userEmail'
CURRENT_ADDRESS_CSS = '#currentAddress'
PERMANENT_ADDRESS_CSS = '#permanentAddress'
SUBMIT_CSS = '#submit'
OUTPUT_BOARD_CSS = '#output'

OUTPUT_RESULT_NAME_CSS = '#name'
OUTPUT_RESULT_EMAIL_CSS = '#email'
OUTPUT_RESULT_CURRENT_ADDRESS_CSS = 'p#currentAddress'
OUTPUT_RESULT_PERMANENT_ADDRESS_CSS = 'p#permanentAddress'