FULL_NAME_XPATH = '//input[@id="userName"]'
EMAIL_XPATH = '//input[@id="userEmail"]'
CURRENT_ADDRESS_XPATH = '//textarea[@id="currentAddress"]'
PERMANENT_ADDRESS_XPATH = '//textarea[@id="permanentAddress"]'
SUBMIT_XPATH = '//button[@id="submit"]'
OUTPUT_BOARD_XPATH = '//div[@id="output"]'

OUTPUT_RESULT_NAME_XPATH = '//p[@id="name"]'
OUTPUT_RESULT_EMAIL_XPATH = '//p[@id="email"]'
OUTPUT_RESULT_CURRENT_ADDRESS_XPATH = '//p[@id="currentAddress"]'
OUTPUT_RESULT_PERMANENT_ADDRESS_XPATH = '//p[@id="permanentAddress"]'
